//
// Created by Arnon Keereena on 2019-04-08.
//

import Foundation

public struct Order: Decodable {
  public var id: String?
  public var email: String?
  public var closedAt: Date?
  public var createdAt: Date?
  public var updatedAt: Date?
  public var number: Int?
  public var note: String?
  public var token: String?
  public var gateway: String?
  public var test: Bool?
  public var totalPrice: String?
  public var subtotalPrice: String?
  public var totalWeight: Int?
  public var totalTax: String?
  public var taxesIncluded: Bool?
  public var currency: String?
  public var financialStatus: String?
  public var confirmed: Bool?
  public var totalDiscounts: String?
  public var totalLineItemsPrice: String?
  public var cartToken: String?
  public var buyerAcceptsMarketing: Bool?
  public var name: String?
  public var referringSite: String?
  public var landingSite: String?
  public var cancelledAt: Date?
  public var cancelReason: String?
  public var totalPriceUsd: String?
  public var checkoutToken: String?
  public var reference: String?
  public var userId: Int?
  public var locationId: Int?
  public var sourceIdentifier: String?
  public var sourceUrl: String?
  public var processedAt: Date?
  public var deviceId: Int?
  public var phone: String?
  public var customerLocale: String?
  public var appId: Int?
  public var browserIp: String?
  public var landingSiteRef: String?
  public var orderNumber: String?
  public var discountApplications: [String]?
  public var discountCodes: [String]?
  public var noteAttributes: [String]?
  public var paymentGatewayNames: [String]?
  public var processingMethod: String?
  public var checkoutId: Int?
  public var sourceName: String?
  public var fulfillmentStatus: String?
  public var taxLines: [TaxLine]?
  public var tags: String?
  public var contactEmail: String?
  public var orderStatusUrl: String?
  public var adminGraphqlApiId: String?
  public var lineItems: [LineItem]?
  public var shippingLines: [ShippingLine]?
  public var billingAddress: BillingAddress
  public var shippingAddress: ShippingAddress
  public var fulfillments: [String]?
  public var clientDetails: ClientDetails
  public var refunds: [String]?
  public var customer: Customer
  public var trackingNumber: String?
  
  enum CodingKeys: String, CodingKey {
    case id = "id"
    case email = "email"
    case closedAt = "closed_at"
    case createdAt = "created_at"
    case updatedAt = "updated_at"
    case number = "number"
    case note = "note"
    case token = "token"
    case gateway = "gateway"
    case test = "test"
    case totalPrice = "total_price"
    case subtotalPrice = "subtotal_price"
    case totalWeight = "total_weight"
    case totalTax = "total_tax"
    case taxesIncluded = "taxes_included"
    case currency = "currency"
    case financialStatus = "financial_status"
    case confirmed = "confirmed"
    case totalDiscounts = "total_discounts"
    case totalLineItemsPrice = "total_line_items_price"
    case cartToken = "cart_token"
    case buyerAcceptsMarketing = "buyer_accepts_marketing"
    case name = "name"
    case referringSite = "referring_site"
    case landingSite = "landing_site"
    case cancelledAt = "cancelled_at"
    case cancelReason = "cancel_reason"
    case totalPriceUsd = "total_price_usd"
    case checkoutToken = "checkout_token"
    case reference = "reference"
    case userId = "user_id"
    case locationId = "location_id"
    case sourceIdentifier = "source_identifier"
    case sourceUrl = "source_url"
    case processedAt = "processed_at"
    case deviceId = "device_id"
    case phone = "phone"
    case customerLocale = "customer_locale"
    case appId = "app_id"
    case browserIp = "browser_ip"
    case landingSiteRef = "landing_site_ref"
    case orderNumber = "order_number"
    case discountApplications = "discount_applications"
    case discountCodes = "discount_codes"
    case noteAttributes = "note_attributes"
    case paymentGatewayNames = "payment_gateway_names"
    case processingMethod = "processing_method"
    case checkoutId = "checkout_id"
    case sourceName = "source_name"
    case fulfillmentStatus = "fulfillment_status"
    case taxLines = "tax_lines"
    case tags = "tags"
    case contactEmail = "contact_email"
    case orderStatusUrl = "order_status_url"
    case adminGraphqlApiId = "admin_graphql_api_id"
    case lineItems = "line_items"
    case shippingLines = "shipping_lines"
    case billingAddress = "billing_address"
    case shippingAddress = "shipping_address"
    case fulfillments = "fulfillments"
    case clientDetails = "client_details"
    case refunds = "refunds"
    case customer = "customer"
    case trackingNumber = "tracking_number"
  }
}
